inherit_from:
  - 'https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml'

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'ffi-libarchive-binary.gemspec'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - 'ports/**/*'

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 160