name: build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.4', '2.5', '2.6', '2.7', '3.0' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]

    steps:
      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake compile

      - if: matrix.os == 'ubuntu-latest'
        run: ldd lib/ffi-libarchive-binary/libarchive.so

      - if: matrix.os == 'windows-latest'
        run: ldd lib/ffi-libarchive-binary/libarchive-13.dll

      - if: matrix.os == 'macos-latest'
        run: otool -L lib/ffi-libarchive-binary/libarchive.dylib

      - run: bundle exec rspec

  pack-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86-mingw32
          - x64-mingw32
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.4'
          bundler-cache: true

      - run: bundle exec rake gem:native:${{ matrix.platform }}

      - run: |
          cd pkg/
          gem unpack ffi-libarchive-binary-*.gem
          ls */lib/ffi-libarchive-binary

  pack-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64-darwin
          - arm64-darwin
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.4'
          bundler-cache: true

      - run: bundle exec rake gem:native:${{ matrix.platform }}

      - run: |
          cd pkg/
          gem unpack ffi-libarchive-binary-*.gem
          ls */lib/ffi-libarchive-binary

  pack-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86-linux
          - x86_64-linux
          - any
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.4'
          bundler-cache: true

      - run: bundle exec rake gem:native:${{ matrix.platform }}

      - run: |
          cd pkg/
          gem unpack ffi-libarchive-binary-*.gem
          ls */lib/ffi-libarchive-binary
