name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  pack:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: x86-mingw32
          - os: windows-latest
            platform: x64-mingw32
          - os: macos-latest
            platform: x86_64-darwin
          - os: macos-latest
            platform: arm64-darwin
          - os: ubuntu-latest
            platform: x86-linux
          - os: ubuntu-latest
            platform: x86_64-linux
          - os: ubuntu-latest
            platform: aarch64-linux
          - os: ubuntu-latest
            platform: any
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'
          bundler-cache: true

      - uses: actions/cache@v2
        with:
          path: ports/archives
          key: ports_archives
          restore-keys: ports_archives

      - if: matrix.platform == 'aarch64-linux'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu gperf

      - run: bundle exec rake gem:native:${{ matrix.platform }}

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-logs-${{ matrix.platform }}
          path: tmp/*/ports/*/*/*.log

      - if: matrix.platform != 'any'
        uses: metanorma/metanorma-build-scripts/native-deps-action@main
        with:
          libname: archive
          directory: lib/ffi-libarchive-binary

      - run: |
          cd pkg/
          gem unpack ffi-libarchive-binary-*.gem
          ls */lib/ffi-libarchive-binary

      - run: gem specification pkg/ffi-libarchive-binary-*.gem

      - uses: actions/upload-artifact@v2
        with:
          name: pkg
          path: pkg/*.gem

      - if: matrix.platform != 'any'
        uses: actions/upload-artifact@v2
        with:
          name: lib-${{ matrix.platform }}
          path: |
            lib/ffi-libarchive-binary/libarchive*

  test:
    needs: pack
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        include:
          - os: windows-latest
            platform: x64-mingw32
          - os: macos-latest
            platform: x86_64-darwin
          - os: ubuntu-latest
            platform: x86_64-linux

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: actions/download-artifact@v2
        with:
          name: lib-${{ matrix.platform }}
          path: lib/ffi-libarchive-binary

      - run: bundle exec rspec

  metanorma:
    needs: pack
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        experimental: [true]
        include:
          - os: windows-latest
            platform: x64-mingw32
          - os: macos-latest
            platform: x86_64-darwin
          - os: ubuntu-latest
            platform: x86_64-linux
    steps:
      - uses: actions/checkout@v2
        with:
          repository: metanorma/metanorma

      - uses: metanorma/metanorma-build-scripts/inkscape-setup-action@main

      - uses: actions/download-artifact@v2
        with:
          name: pkg
          path: pkg

      - name: Setup ffi-libarchive-binary
        run: |
          gem unpack --target pkg pkg/ffi-libarchive-binary-*-${{ matrix.platform }}.gem
          mv pkg/ffi-libarchive-binary-*-${{ matrix.platform }} pkg/ffi-libarchive-binary
          echo "gem 'ffi-libarchive-binary', path: 'pkg/ffi-libarchive-binary'" > Gemfile.devel

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake
